name: Test iOS Versions

on:
  # Run at 1 AM UTC daily
  schedule:
    - cron: "0 1 * * *"
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test-ios-versions:
    name: iOS ${{ matrix.ios-version }}
    runs-on: ubuntu-latest

    strategy:
      # Don't cancel all jobs if one fails
      fail-fast: false
      matrix:
        ios-version:
          - "16" # iOS 16
          - "17" # iOS 17
          - "18" # iOS 18

    steps:
      - uses: actions/checkout@v3

      - name: Run iOS Version Tests
        uses: devicecloud-dev/device-cloud-for-maestro@v1
        with:
          api-key: ${{ secrets.DCD_API_KEY }}
          app-file: binaries/sample.zip
          workspace: ../ios-flow.yaml
          ios-device: iPhone-16
          ios-version: ${{ matrix.ios-version }}
          name: "iOS ${{ matrix.ios-version }} - iPhone 16 Test Run"
