name: Test iOS Versions

on:
  # Run at 1 AM UTC daily
  schedule:
    - cron: "0 1 * * *"
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        type: choice
        options:
          - prod
          - dev
        default: "prod"
        required: true

jobs:
  test-ios-versions:
    name: iOS ${{ matrix.ios-version }}
    runs-on: ubuntu-latest

    strategy:
      # Don't cancel all jobs if one fails
      fail-fast: false
      matrix:
        ios-version:
          - "16" # iOS 16
          - "17" # iOS 17
          - "18" # iOS 18

    steps:
      - uses: actions/checkout@v3

      - name: Run iOS Version Tests
        uses: devicecloud-dev/device-cloud-for-maestro@v1
        with:
          api-key: ${{ github.event.inputs.environment == 'dev' && secrets.DCD_DEV_API_KEY || secrets.DCD_API_KEY }}
          api-url: ${{ github.event.inputs.environment == 'dev' && 'https://api.dev.devicecloud.dev' || '' }}
          app-file: ./binaries/sample.zip
          workspace: ./flows/ios-flow.yaml
          ios-device: iphone-14
          ios-version: ${{ matrix.ios-version }}
          name: "iOS ${{ matrix.ios-version }} - iPhone 14 Test Run"
